# fly.toml 配置文件
app = "gemini-balance-24k1erqreq"  # 替换为你的应用名（需唯一）
primary_region = "sin"  # 主部署区域（如美国东部：iad，可根据用户分布选择）

[build]
  # 指定 Dockerfile 路径（默认当前目录的 Dockerfile）
  dockerfile = "Dockerfile"

[env]
  # 可在此添加环境变量（对应 Docker 容器内的环境变量）
  # 例如：APP_ENV = "production"

[http_service]
  # 配置 HTTP 服务，对应 Dockerfile 暴露的 8000 端口
  internal_port = 8000  # 容器内部端口（需与 Dockerfile 的 EXPOSE 一致）
  force_https = true    # 强制 HTTPS 访问
  auto_stop_machines = true  # 无流量时自动停止机器（节省资源）
  auto_start_machines = true # 有流量时自动启动机器
  min_machines_running = 0   # 最小运行机器数（0 表示可完全停止）
  processes = ["app"]        # 关联的进程（默认 "app"）

[[services]]
  # 底层服务配置，映射外部端口到容器端口
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80  # 外部 HTTP 端口（自动转发到 HTTPS）
    handlers = ["http_redirect"]  # 重定向到 HTTPS

  [[services.ports]]
    port = 443  # 外部 HTTPS 端口
    handlers = ["tls", "http"]  # 启用 TLS 加密和 HTTP 处理

  [[services.tcp_checks]]
    # 健康检查配置（确保服务正常运行）
    interval = "10s"    # 检查间隔
    timeout = "2s"      # 超时时间
    grace_period = "5s" # 启动后 grace 时间（避免立即检查）
